language: java

jdk:
  - oraclejdk8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install: mvn install -B sonar:sonar -Dsonar.login=${SONAR_TOKEN}

after_success: ./report.sh

after_failure: ./report.sh

notifications:
  email:
    recipients:
      - stuart.r.wilson@gmail.com
    on_success: always
    on_failure: always
